mqtt:
  host: 0.0.0.0 # mqtt broker server
  port: 1883
  #user: ""
  #password: ""
  topic_prefix: pimqttgpio/garage_pi

gpio_modules:
  - name: raspberrypi
    module: raspberrypi
    cleanup: yes  # This optional boolean value sets whether the module's `cleanup()` function will be called when the software exits.

digital_inputs:
  - name: Prox_001
    module: raspberrypi
    pin: 18  # This device is connected to pin 18 of the Raspberry PI GPIO
    on_payload: "ON"
    off_payload: "OFF"
    pullup: no
    pulldown: yes
    retain: yes

digital_outputs:
  - name: relay_001
    module: raspberrypi
    pin: 5  # This device is connected to pin 2 of the PCF8574 IO expander
    on_payload: "ON"
    off_payload: "OFF"
    initial: high  # This optional value controls the initial state of the pin before receipt of any messages from MQTT. Valid options are 'low' and 'high'.
    retain: yes # This option value controls if the message is retained. Default is no.
